CREATE TABLE Country (Id  SERIAL NOT NULL, Code VARCHAR(50) NOT NULL, ExternalId VARCHAR(36) NOT NULL UNIQUE, Name VARCHAR(50) NOT NULL, PRIMARY KEY (Id))
CREATE TABLE Language (Id  SERIAL NOT NULL, Code VARCHAR(50) NOT NULL, ExternalId VARCHAR(36) NOT NULL UNIQUE, Name VARCHAR(50) NOT NULL, NativeName VARCHAR(50) NOT NULL, PRIMARY KEY (Id))
