CREATE TABLE Country (Id  SERIAL NOT NULL, Code VARCHAR(50) NOT NULL, ExternalId VARCHAR(36) NOT NULL UNIQUE, Name VARCHAR(50) NOT NULL, PRIMARY KEY (Id))
CREATE TABLE LANGUAGE (_ID  SERIAL NOT NULL, _CODE VARCHAR(255), _EXTERNALID BYTEA, _NAME VARCHAR(255), _NATIVENAME VARCHAR(255), PRIMARY KEY (_ID))
