CREATE TABLE Country (Id BIGINT NOT NULL, Code VARCHAR(50) NOT NULL, ExternalId VARCHAR(36) NOT NULL UNIQUE, Name VARCHAR(50) NOT NULL, PRIMARY KEY (Id))
CREATE TABLE Language (Id BIGINT NOT NULL, Code VARCHAR(50) NOT NULL, ExternalId VARCHAR(36) NOT NULL UNIQUE, Name VARCHAR(50) NOT NULL, NativeName VARCHAR(50) NOT NULL, PRIMARY KEY (Id))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
